### ISSUE TITLE
Create service to reset odometry

### ISSUE THREAD

**Issue by valeperi** [LeoBoticsHub/unitree_ros2_to_real#1]
Create a service that, when called, resets the odometry to 0. This service is necessary to start the odometry computation from scratch, addressing the issue of cumulative odometry error in the robot.

**Comment by FedericoRollo** [comment]
The issue has been solved. The service ```reset_odom``` has been added.

**Comment by FedericoRollo** [comment]
A possible solution for resetting also the robot orientation is the following https://gamedev.stackexchange.com/questions/28395/rotating-vector3-by-a-quaternion .

It could be useful to also have the zeroing of rotations for future purposes. Does it make any sense?
